//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Domain.RealState.Owners.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealState.Domain.RealState.Owners.Resources.CodesResources", typeof(CodesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerAlreadyActive.
        /// </summary>
        internal static string OwnerAlreadyActive {
            get {
                return ResourceManager.GetString("OwnerAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerAlreadyInactive.
        /// </summary>
        internal static string OwnerAlreadyInactive {
            get {
                return ResourceManager.GetString("OwnerAlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerBirthdayInvalid.
        /// </summary>
        internal static string OwnerBirthdayInvalid {
            get {
                return ResourceManager.GetString("OwnerBirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerDuplicate.
        /// </summary>
        internal static string OwnerConflict {
            get {
                return ResourceManager.GetString("OwnerConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerDataInvalid.
        /// </summary>
        internal static string OwnerDataInvalid {
            get {
                return ResourceManager.GetString("OwnerDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerHasLinkedProperties.
        /// </summary>
        internal static string OwnerHasLinkedProperties {
            get {
                return ResourceManager.GetString("OwnerHasLinkedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerNotFound.
        /// </summary>
        internal static string OwnerNotFound {
            get {
                return ResourceManager.GetString("OwnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerPhotoInvalid.
        /// </summary>
        internal static string OwnerPhotoInvalid {
            get {
                return ResourceManager.GetString("OwnerPhotoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyNotFound.
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
    }
}
