//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Domain.RealState.Owners.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OwnersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealState.Domain.RealState.Owners.Resources.OwnersResources", typeof(OwnersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de cumpleaños &apos;{0}&apos; no es válida (no puede ser futura)..
        /// </summary>
        internal static string OwnerBirthdayInvalid {
            get {
                return ResourceManager.GetString("OwnerBirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un propietario con el nombre ingresado..
        /// </summary>
        internal static string OwnerConflict_Name {
            get {
                return ResourceManager.GetString("OwnerConflict_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del propietario proporcionados son inválidos o están incompletos..
        /// </summary>
        internal static string OwnerDataInvalid {
            get {
                return ResourceManager.GetString("OwnerDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El propietario tiene propiedades asociadas y no puede eliminarse..
        /// </summary>
        internal static string OwnerHasLinkedProperties {
            get {
                return ResourceManager.GetString("OwnerHasLinkedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró un propietario con el Id ingresado..
        /// </summary>
        internal static string OwnerNotFound_Id {
            get {
                return ResourceManager.GetString("OwnerNotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró un propietario con el nombre ingresado.
        /// </summary>
        internal static string OwnerNotFound_Name {
            get {
                return ResourceManager.GetString("OwnerNotFound_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La foto debe ser una URL válida o una imagen en Base64..
        /// </summary>
        internal static string OwnerPhotoInvalid {
            get {
                return ResourceManager.GetString("OwnerPhotoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una propiedad con el Id ingresado..
        /// </summary>
        internal static string PropertyNotFound_Id {
            get {
                return ResourceManager.GetString("PropertyNotFound_Id", resourceCulture);
            }
        }
    }
}
