//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Application.UseCase.Owners.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OwnerListValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnerListValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealState.Application.UseCase.Owners.Resource.OwnerListValidationResource", typeof(OwnerListValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rango de cumpleaños es inválido..
        /// </summary>
        internal static string InvalidBirthdayRange {
            get {
                return ResourceManager.GetString("InvalidBirthdayRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rango de fechas de creación es inválido..
        /// </summary>
        internal static string InvalidCreatedRange {
            get {
                return ResourceManager.GetString("InvalidCreatedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La página debe ser mayor o igual a 1..
        /// </summary>
        internal static string InvalidPage {
            get {
                return ResourceManager.GetString("InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de página debe estar entre 1 y 200..
        /// </summary>
        internal static string InvalidPageSize {
            get {
                return ResourceManager.GetString("InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo de ordenamiento no es válido..
        /// </summary>
        internal static string InvalidSortBy {
            get {
                return ResourceManager.GetString("InvalidSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de ordenamiento debe ser ‘asc’ o ‘desc’..
        /// </summary>
        internal static string InvalidSortDir {
            get {
                return ResourceManager.GetString("InvalidSortDir", resourceCulture);
            }
        }
    }
}
