//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Domain.RealState.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealState.Domain.RealState.Properties.Resources.CodeResources", typeof(CodeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.OwnerNotFound.
        /// </summary>
        internal static string OwnerNotFound {
            get {
                return ResourceManager.GetString("OwnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyAddressInvalid.
        /// </summary>
        internal static string PropertyAddressInvalid {
            get {
                return ResourceManager.GetString("PropertyAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyConflict.
        /// </summary>
        internal static string PropertyConflict {
            get {
                return ResourceManager.GetString("PropertyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyDataInvalid.
        /// </summary>
        internal static string PropertyDataInvalid {
            get {
                return ResourceManager.GetString("PropertyDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyImageConflict.
        /// </summary>
        internal static string PropertyImageConflict {
            get {
                return ResourceManager.GetString("PropertyImageConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyImageDataInvalid.
        /// </summary>
        internal static string PropertyImageDataInvalid {
            get {
                return ResourceManager.GetString("PropertyImageDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyImageInvalid.
        /// </summary>
        internal static string PropertyImageInvalid {
            get {
                return ResourceManager.GetString("PropertyImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyImageNotFound.
        /// </summary>
        internal static string PropertyImageNotFound {
            get {
                return ResourceManager.GetString("PropertyImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyImageUploadFailed.
        /// </summary>
        internal static string PropertyImageUploadFailed {
            get {
                return ResourceManager.GetString("PropertyImageUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyNotFound.
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyPriceInvalid.
        /// </summary>
        internal static string PropertyPriceInvalid {
            get {
                return ResourceManager.GetString("PropertyPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyTraceDataInvalid.
        /// </summary>
        internal static string PropertyTraceDataInvalid {
            get {
                return ResourceManager.GetString("PropertyTraceDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealState.PropertyYearInvalid.
        /// </summary>
        internal static string PropertyYearInvalid {
            get {
                return ResourceManager.GetString("PropertyYearInvalid", resourceCulture);
            }
        }
    }
}
