//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Domain.RealState.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealState.Domain.RealState.Properties.Resources.PropertiesResources", typeof(PropertiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró un propietario con el Id ingresado..
        /// </summary>
        internal static string OwnerNotFound_Id {
            get {
                return ResourceManager.GetString("OwnerNotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección es obligatoria..
        /// </summary>
        internal static string PropertyAddressInvalid {
            get {
                return ResourceManager.GetString("PropertyAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una propiedad con el código interno &apos;{0}&apos;..
        /// </summary>
        internal static string PropertyConflict_Code {
            get {
                return ResourceManager.GetString("PropertyConflict_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de la propiedad proporcionados son inválidos o están incompletos..
        /// </summary>
        internal static string PropertyDataInvalid {
            get {
                return ResourceManager.GetString("PropertyDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una imagen con el mismo archivo/nombre ‘{0}’ para esta propiedad..
        /// </summary>
        internal static string PropertyImageConflict_File {
            get {
                return ResourceManager.GetString("PropertyImageConflict_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de la imagen de la propiedad son inválidos o están incompletos..
        /// </summary>
        internal static string PropertyImageDataInvalid {
            get {
                return ResourceManager.GetString("PropertyImageDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo de imagen es inválido o su formato no es permitido..
        /// </summary>
        internal static string PropertyImageInvalid {
            get {
                return ResourceManager.GetString("PropertyImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una imagen con el Id ingresado..
        /// </summary>
        internal static string PropertyImageNotFound_Id {
            get {
                return ResourceManager.GetString("PropertyImageNotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cargar la imagen..
        /// </summary>
        internal static string PropertyImageUploadFailed {
            get {
                return ResourceManager.GetString("PropertyImageUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una propiedad con el Id ingresado..
        /// </summary>
        internal static string PropertyNotFound_Id {
            get {
                return ResourceManager.GetString("PropertyNotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio &apos;{0}&apos; no es válido (debe ser mayor a cero)..
        /// </summary>
        internal static string PropertyPriceInvalid {
            get {
                return ResourceManager.GetString("PropertyPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de la traza de propiedad son inválidos o están incompletos..
        /// </summary>
        internal static string PropertyTraceDataInvalid {
            get {
                return ResourceManager.GetString("PropertyTraceDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El año &apos;{0}&apos; no es válido..
        /// </summary>
        internal static string PropertyYearInvalid {
            get {
                return ResourceManager.GetString("PropertyYearInvalid", resourceCulture);
            }
        }
    }
}
