//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Application.UseCase.Properties.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealState.Application.UseCase.Properties.Resource.PropertyValidationResource", typeof(PropertyValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio debe ser mayor que cero..
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El año especificado no es válido..
        /// </summary>
        internal static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección no debe exceder 300 caracteres..
        /// </summary>
        internal static string MaxCharAddress {
            get {
                return ResourceManager.GetString("MaxCharAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código interno no debe exceder 100 caracteres..
        /// </summary>
        internal static string MaxCharCode {
            get {
                return ResourceManager.GetString("MaxCharCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no debe exceder 200 caracteres..
        /// </summary>
        internal static string MaxCharName {
            get {
                return ResourceManager.GetString("MaxCharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección es obligatoria..
        /// </summary>
        internal static string NotOptionalAddress {
            get {
                return ResourceManager.GetString("NotOptionalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código interno es obligatorio..
        /// </summary>
        internal static string NotOptionalCodeInternal {
            get {
                return ResourceManager.GetString("NotOptionalCodeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador es obligatorio..
        /// </summary>
        internal static string NotOptionalId {
            get {
                return ResourceManager.GetString("NotOptionalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio..
        /// </summary>
        internal static string NotOptionalName {
            get {
                return ResourceManager.GetString("NotOptionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El propietario es obligatorio..
        /// </summary>
        internal static string NotOptionalOwner {
            get {
                return ResourceManager.GetString("NotOptionalOwner", resourceCulture);
            }
        }
    }
}
